package api

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Envelope) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	{
		var zb0002 uint8
		zb0002, err = dc.ReadUint8()
		if err != nil {
			err = msgp.WrapError(err, "Type")
			return
		}
		z.Type = MessageType(zb0002)
	}
	err = z.Data.DecodeMsg(dc)
	if err != nil {
		err = msgp.WrapError(err, "Data")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Envelope) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	err = en.WriteUint8(uint8(z.Type))
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	err = z.Data.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Data")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Envelope) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o = msgp.AppendUint8(o, uint8(z.Type))
	o, err = z.Data.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Data")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Envelope) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	{
		var zb0002 uint8
		zb0002, bts, err = msgp.ReadUint8Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err, "Type")
			return
		}
		z.Type = MessageType(zb0002)
	}
	bts, err = z.Data.UnmarshalMsg(bts)
	if err != nil {
		err = msgp.WrapError(err, "Data")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Envelope) Msgsize() (s int) {
	s = 1 + msgp.Uint8Size + z.Data.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *IdleItem) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "delay":
			z.Delay, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "Delay")
				return
			}
		case "idle":
			z.IdleAction, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "IdleAction")
				return
			}
		case "resume":
			z.ResumeAction, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ResumeAction")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z IdleItem) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "delay"
	err = en.Append(0x83, 0xa5, 0x64, 0x65, 0x6c, 0x61, 0x79)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.Delay)
	if err != nil {
		err = msgp.WrapError(err, "Delay")
		return
	}
	// write "idle"
	err = en.Append(0xa4, 0x69, 0x64, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.IdleAction)
	if err != nil {
		err = msgp.WrapError(err, "IdleAction")
		return
	}
	// write "resume"
	err = en.Append(0xa6, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.ResumeAction)
	if err != nil {
		err = msgp.WrapError(err, "ResumeAction")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z IdleItem) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "delay"
	o = append(o, 0x83, 0xa5, 0x64, 0x65, 0x6c, 0x61, 0x79)
	o = msgp.AppendUint32(o, z.Delay)
	// string "idle"
	o = append(o, 0xa4, 0x69, 0x64, 0x6c, 0x65)
	o = msgp.AppendString(o, z.IdleAction)
	// string "resume"
	o = append(o, 0xa6, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65)
	o = msgp.AppendString(o, z.ResumeAction)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *IdleItem) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "delay":
			z.Delay, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Delay")
				return
			}
		case "idle":
			z.IdleAction, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IdleAction")
				return
			}
		case "resume":
			z.ResumeAction, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ResumeAction")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z IdleItem) Msgsize() (s int) {
	s = 1 + 6 + msgp.Uint32Size + 5 + msgp.StringPrefixSize + len(z.IdleAction) + 7 + msgp.StringPrefixSize + len(z.ResumeAction)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 uint8
		zb0001, err = dc.ReadUint8()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = MessageType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z MessageType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteUint8(uint8(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z MessageType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendUint8(o, uint8(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 uint8
		zb0001, bts, err = msgp.ReadUint8Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = MessageType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z MessageType) Msgsize() (s int) {
	s = msgp.Uint8Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NotifyBarrelStatus) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	err = z.Target.DecodeMsg(dc)
	if err != nil {
		err = msgp.WrapError(err, "Target")
		return
	}
	err = z.Lifecycle.DecodeMsg(dc)
	if err != nil {
		err = msgp.WrapError(err, "Lifecycle")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *NotifyBarrelStatus) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	err = z.Target.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Target")
		return
	}
	err = z.Lifecycle.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Lifecycle")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *NotifyBarrelStatus) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o, err = z.Target.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Target")
		return
	}
	o, err = z.Lifecycle.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Lifecycle")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NotifyBarrelStatus) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	bts, err = z.Target.UnmarshalMsg(bts)
	if err != nil {
		err = msgp.WrapError(err, "Target")
		return
	}
	bts, err = z.Lifecycle.UnmarshalMsg(bts)
	if err != nil {
		err = msgp.WrapError(err, "Lifecycle")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NotifyBarrelStatus) Msgsize() (s int) {
	s = 1 + z.Target.Msgsize() + z.Lifecycle.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RequestListIdle) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z RequestListIdle) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 0
	_ = z
	err = en.Append(0x80)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z RequestListIdle) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 0
	_ = z
	o = append(o, 0x80)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RequestListIdle) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z RequestListIdle) Msgsize() (s int) {
	s = 1
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RequestStatus) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z RequestStatus) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 0
	_ = z
	err = en.Append(0x80)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z RequestStatus) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 0
	_ = z
	o = append(o, 0x80)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RequestStatus) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z RequestStatus) Msgsize() (s int) {
	s = 1
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ResponseListIdle) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "items":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Items")
				return
			}
			if cap(z.Items) >= int(zb0002) {
				z.Items = (z.Items)[:zb0002]
			} else {
				z.Items = make([]IdleItem, zb0002)
			}
			for za0001 := range z.Items {
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Items", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Items", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "delay":
						z.Items[za0001].Delay, err = dc.ReadUint32()
						if err != nil {
							err = msgp.WrapError(err, "Items", za0001, "Delay")
							return
						}
					case "idle":
						z.Items[za0001].IdleAction, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "Items", za0001, "IdleAction")
							return
						}
					case "resume":
						z.Items[za0001].ResumeAction, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "Items", za0001, "ResumeAction")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Items", za0001)
							return
						}
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ResponseListIdle) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "items"
	err = en.Append(0x81, 0xa5, 0x69, 0x74, 0x65, 0x6d, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Items)))
	if err != nil {
		err = msgp.WrapError(err, "Items")
		return
	}
	for za0001 := range z.Items {
		// map header, size 3
		// write "delay"
		err = en.Append(0x83, 0xa5, 0x64, 0x65, 0x6c, 0x61, 0x79)
		if err != nil {
			return
		}
		err = en.WriteUint32(z.Items[za0001].Delay)
		if err != nil {
			err = msgp.WrapError(err, "Items", za0001, "Delay")
			return
		}
		// write "idle"
		err = en.Append(0xa4, 0x69, 0x64, 0x6c, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.Items[za0001].IdleAction)
		if err != nil {
			err = msgp.WrapError(err, "Items", za0001, "IdleAction")
			return
		}
		// write "resume"
		err = en.Append(0xa6, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.Items[za0001].ResumeAction)
		if err != nil {
			err = msgp.WrapError(err, "Items", za0001, "ResumeAction")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ResponseListIdle) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "items"
	o = append(o, 0x81, 0xa5, 0x69, 0x74, 0x65, 0x6d, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Items)))
	for za0001 := range z.Items {
		// map header, size 3
		// string "delay"
		o = append(o, 0x83, 0xa5, 0x64, 0x65, 0x6c, 0x61, 0x79)
		o = msgp.AppendUint32(o, z.Items[za0001].Delay)
		// string "idle"
		o = append(o, 0xa4, 0x69, 0x64, 0x6c, 0x65)
		o = msgp.AppendString(o, z.Items[za0001].IdleAction)
		// string "resume"
		o = append(o, 0xa6, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65)
		o = msgp.AppendString(o, z.Items[za0001].ResumeAction)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ResponseListIdle) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "items":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Items")
				return
			}
			if cap(z.Items) >= int(zb0002) {
				z.Items = (z.Items)[:zb0002]
			} else {
				z.Items = make([]IdleItem, zb0002)
			}
			for za0001 := range z.Items {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Items", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Items", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "delay":
						z.Items[za0001].Delay, bts, err = msgp.ReadUint32Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Items", za0001, "Delay")
							return
						}
					case "idle":
						z.Items[za0001].IdleAction, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Items", za0001, "IdleAction")
							return
						}
					case "resume":
						z.Items[za0001].ResumeAction, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Items", za0001, "ResumeAction")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Items", za0001)
							return
						}
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ResponseListIdle) Msgsize() (s int) {
	s = 1 + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Items {
		s += 1 + 6 + msgp.Uint32Size + 5 + msgp.StringPrefixSize + len(z.Items[za0001].IdleAction) + 7 + msgp.StringPrefixSize + len(z.Items[za0001].ResumeAction)
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ResponseStatus) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "enabled":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Enabled")
				return
			}
			if cap(z.Enabled) >= int(zb0002) {
				z.Enabled = (z.Enabled)[:zb0002]
			} else {
				z.Enabled = make([]string, zb0002)
			}
			for za0001 := range z.Enabled {
				z.Enabled[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Enabled", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ResponseStatus) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "enabled"
	err = en.Append(0x81, 0xa7, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Enabled)))
	if err != nil {
		err = msgp.WrapError(err, "Enabled")
		return
	}
	for za0001 := range z.Enabled {
		err = en.WriteString(z.Enabled[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Enabled", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ResponseStatus) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "enabled"
	o = append(o, 0x81, 0xa7, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Enabled)))
	for za0001 := range z.Enabled {
		o = msgp.AppendString(o, z.Enabled[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ResponseStatus) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "enabled":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Enabled")
				return
			}
			if cap(z.Enabled) >= int(zb0002) {
				z.Enabled = (z.Enabled)[:zb0002]
			} else {
				z.Enabled = make([]string, zb0002)
			}
			for za0001 := range z.Enabled {
				z.Enabled[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Enabled", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ResponseStatus) Msgsize() (s int) {
	s = 1 + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Enabled {
		s += msgp.StringPrefixSize + len(z.Enabled[za0001])
	}
	return
}
